/* Configuration master data — UI only.
 *
 * Every row here is a *specification* of the reference data a deployment has to
 * supply, kept beside the page that shows it. Nothing in this file is read by
 * the engine, no row reaches a database, and no module imports it: the intake
 * gazetteer, the commodity taxonomy and the procedure corpus remain the only
 * things the product actually runs on. When a registry becomes real it moves
 * out of here and the page reads it like any other screen.
 *
 * Counts are the authored figures, not a length — they are what the tier
 * summary on the index promises, so a row added by hand does not silently
 * change the headline. */

export type Column = { key: string; label: string; wide?: boolean; numeric?: boolean };

export type Registry = {
  slug: string;
  name: string;
  blurb: string;
  /** Authored registries must be filled in before the first shipment; the rest
   *  are read from the published corpus and cannot be edited here. */
  authored: boolean;
  /** Where a read-only registry comes from. */
  source: string | null;
  columns: Column[];
  rows: Record<string, string | number>[];
};

const COUNTRIES: Registry = {
  slug: "countries",
  name: "Countries & destinations",
  blurb: "Trade partners, the origin proof each expects, and the destination rules that decide what a shipment needs.",
  authored: true,
  source: null,
  columns: [{"key": "code", "label": "ISO"}, {"key": "name", "label": "Country"}, {"key": "region", "label": "Region"}, {"key": "eaeu", "label": "EAEU"}, {"key": "originProof", "label": "Origin proof"}, {"key": "crossings", "label": "Crossing points"}, {"key": "requirements", "label": "Destination requirements", "wide": true}],
  rows: [
    {"code": "UZ", "name": "Uzbekistan", "region": "Central Asia", "eaeu": "—", "originProof": "—", "crossings": "—", "requirements": "—"},
    {"code": "KZ", "name": "Kazakhstan", "region": "Central Asia", "eaeu": "member", "originProof": "Form CT-1", "crossings": "Gisht-Ko'prik, Yallama, Daut-Ata", "requirements": "Phytosanitary certificate for fresh produce · Fumigation for wooden packaging (ISPM 15)"},
    {"code": "KG", "name": "Kyrgyzstan", "region": "Central Asia", "eaeu": "member", "originProof": "Form CT-1", "crossings": "Dostuk, Uch-Kurgan", "requirements": "Phytosanitary certificate for fresh produce"},
    {"code": "TR", "name": "Türkiye", "region": "Western Asia", "eaeu": "—", "originProof": "Form A / EUR.1", "crossings": "—  sea and air routes", "requirements": "Veterinary certificate for animal products · Food test report from an accredited laboratory"},
    {"code": "AF", "name": "Afghanistan", "region": "South Asia", "eaeu": "—", "originProof": "Certificate of origin (general form)", "crossings": "Termez / Hairatan", "requirements": "Transit declaration for onward movement"},
    {"code": "RU", "name": "Russia", "region": "Eastern Europe", "eaeu": "member", "originProof": "Form CT-1", "crossings": "via Kazakhstan", "requirements": "Phytosanitary certificate for fresh produce"},
    {"code": "CN", "name": "China", "region": "East Asia", "eaeu": "—", "originProof": "Form A", "crossings": "via Kyrgyzstan / Kazakhstan", "requirements": "Registration of the exporter with GACC for foodstuffs"},
  ],
};

const CURRENCIES: Registry = {
  slug: "currencies",
  name: "Currencies",
  blurb: "Currencies a contract may be denominated in, and which may settle a fee locally.",
  authored: true,
  source: null,
  columns: [{"key": "code", "label": "Code"}, {"key": "name", "label": "Currency"}, {"key": "symbol", "label": "Symbol"}, {"key": "domestic", "label": "Settles fees locally"}],
  rows: [
    {"code": "UZS", "name": "Uzbek sum", "symbol": "so'm", "domestic": "yes"},
    {"code": "USD", "name": "US dollar", "symbol": "$$", "domestic": "no"},
    {"code": "EUR", "name": "Euro", "symbol": "€", "domestic": "no"},
    {"code": "KZT", "name": "Kazakhstani tenge", "symbol": "₸", "domestic": "no"},
    {"code": "TRY", "name": "Turkish lira", "symbol": "₺", "domestic": "no"},
    {"code": "RUB", "name": "Russian rouble", "symbol": "₽", "domestic": "no"},
    {"code": "CNY", "name": "Chinese yuan", "symbol": "¥", "domestic": "no"},
  ],
};

const COMMODITY_CODES: Registry = {
  slug: "commodity-codes",
  name: "Commodity codes",
  blurb: "HS codes, and the regulatory regime each one drags in behind it. The regime is what lets an agent infer a procedure from a sentence about tomatoes — the most consequential registry here.",
  authored: true,
  source: null,
  columns: [{"key": "hs", "label": "HS"}, {"key": "description", "label": "Description", "wide": true}, {"key": "group", "label": "Group"}, {"key": "regime", "label": "Regime"}],
  rows: [
    {"hs": "0102 21", "description": "Cattle, purebred breeding animals", "group": "Live animals", "regime": "Veterinary"},
    {"hs": "0104 10", "description": "Sheep, live", "group": "Live animals", "regime": "Veterinary"},
    {"hs": "0105 11", "description": "Fowls of the species Gallus domesticus, weighing ≤ 185 g", "group": "Live animals", "regime": "Veterinary"},
    {"hs": "0201 30", "description": "Meat of bovine animals, boneless, fresh or chilled", "group": "Meat", "regime": "Veterinary"},
    {"hs": "0202 30", "description": "Meat of bovine animals, boneless, frozen", "group": "Meat", "regime": "Veterinary"},
    {"hs": "0204 42", "description": "Meat of sheep, other cuts with bone in, frozen", "group": "Meat", "regime": "Veterinary"},
    {"hs": "0207 12", "description": "Meat of fowls, not cut in pieces, frozen", "group": "Meat", "regime": "Veterinary"},
    {"hs": "0207 14", "description": "Cuts and edible offal of fowls, frozen", "group": "Meat", "regime": "Veterinary"},
    {"hs": "0301 93", "description": "Carp, live", "group": "Fish", "regime": "Veterinary"},
    {"hs": "0302 11", "description": "Trout, fresh or chilled", "group": "Fish", "regime": "Veterinary"},
    {"hs": "0303 14", "description": "Trout, frozen", "group": "Fish", "regime": "Veterinary"},
    {"hs": "0401 20", "description": "Milk and cream, fat content 1–6 %, not concentrated", "group": "Dairy", "regime": "Veterinary"},
    {"hs": "0402 10", "description": "Milk and cream in powder, fat content ≤ 1.5 %", "group": "Dairy", "regime": "Veterinary"},
    {"hs": "0403 20", "description": "Yogurt", "group": "Dairy", "regime": "Veterinary"},
    {"hs": "0405 10", "description": "Butter", "group": "Dairy", "regime": "Veterinary"},
    {"hs": "0406 10", "description": "Fresh cheese, including whey cheese, and curd", "group": "Dairy", "regime": "Veterinary"},
    {"hs": "0406 90", "description": "Cheese, other", "group": "Dairy", "regime": "Veterinary"},
    {"hs": "0407 21", "description": "Eggs of fowls, fresh, for consumption", "group": "Dairy", "regime": "Veterinary"},
    {"hs": "0409 00", "description": "Natural honey", "group": "Dairy", "regime": "Veterinary"},
    {"hs": "0602 90", "description": "Live plants, other", "group": "Live plants", "regime": "Phytosanitary"},
    {"hs": "0603 11", "description": "Roses, fresh cut", "group": "Live plants", "regime": "Phytosanitary"},
    {"hs": "0701 90", "description": "Potatoes, fresh or chilled, other", "group": "Vegetables", "regime": "Phytosanitary"},
    {"hs": "0702 00", "description": "Tomatoes, fresh or chilled", "group": "Vegetables", "regime": "Phytosanitary"},
    {"hs": "0703 10", "description": "Onions and shallots, fresh or chilled", "group": "Vegetables", "regime": "Phytosanitary"},
    {"hs": "0703 20", "description": "Garlic, fresh or chilled", "group": "Vegetables", "regime": "Phytosanitary"},
    {"hs": "0704 90", "description": "Cabbages and similar brassicas, fresh or chilled, other", "group": "Vegetables", "regime": "Phytosanitary"},
    {"hs": "0706 10", "description": "Carrots and turnips, fresh or chilled", "group": "Vegetables", "regime": "Phytosanitary"},
    {"hs": "0707 00", "description": "Cucumbers and gherkins, fresh or chilled", "group": "Vegetables", "regime": "Phytosanitary"},
    {"hs": "0709 30", "description": "Aubergines (egg-plants), fresh or chilled", "group": "Vegetables", "regime": "Phytosanitary"},
    {"hs": "0709 60", "description": "Peppers of the genus Capsicum, fresh or chilled", "group": "Vegetables", "regime": "Phytosanitary"},
    {"hs": "0710 80", "description": "Vegetables, frozen, other", "group": "Vegetables", "regime": "Phytosanitary"},
    {"hs": "0712 90", "description": "Dried vegetables, other", "group": "Vegetables", "regime": "Phytosanitary"},
    {"hs": "0713 31", "description": "Beans of the Vigna mungo or Vigna radiata species, dried", "group": "Pulses", "regime": "Phytosanitary"},
    {"hs": "0713 40", "description": "Lentils, dried", "group": "Pulses", "regime": "Phytosanitary"},
    {"hs": "0802 12", "description": "Almonds, fresh or dried, shelled", "group": "Nuts", "regime": "Phytosanitary"},
    {"hs": "0802 32", "description": "Walnuts, fresh or dried, shelled", "group": "Nuts", "regime": "Phytosanitary"},
    {"hs": "0802 51", "description": "Pistachios, fresh or dried, in shell", "group": "Nuts", "regime": "Phytosanitary"},
    {"hs": "0802 52", "description": "Pistachios, fresh or dried, shelled", "group": "Nuts", "regime": "Phytosanitary"},
    {"hs": "0804 10", "description": "Dates, fresh or dried", "group": "Fruit", "regime": "Phytosanitary"},
    {"hs": "0805 10", "description": "Oranges, fresh or dried", "group": "Fruit", "regime": "Phytosanitary"},
    {"hs": "0805 50", "description": "Lemons and limes, fresh or dried", "group": "Fruit", "regime": "Phytosanitary"},
    {"hs": "0806 10", "description": "Grapes, fresh", "group": "Fruit", "regime": "Phytosanitary"},
    {"hs": "0806 20", "description": "Grapes, dried (raisins)", "group": "Dried fruit", "regime": "Phytosanitary"},
    {"hs": "0807 11", "description": "Watermelons, fresh", "group": "Fruit", "regime": "Phytosanitary"},
    {"hs": "0807 19", "description": "Melons, fresh, other", "group": "Fruit", "regime": "Phytosanitary"},
    {"hs": "0808 10", "description": "Apples, fresh", "group": "Fruit", "regime": "Phytosanitary"},
    {"hs": "0808 30", "description": "Pears, fresh", "group": "Fruit", "regime": "Phytosanitary"},
    {"hs": "0809 10", "description": "Apricots, fresh", "group": "Fruit", "regime": "Phytosanitary"},
    {"hs": "0809 21", "description": "Sour cherries (Prunus cerasus), fresh", "group": "Fruit", "regime": "Phytosanitary"},
    {"hs": "0809 29", "description": "Cherries, fresh, other", "group": "Fruit", "regime": "Phytosanitary"},
    {"hs": "0809 30", "description": "Peaches, including nectarines, fresh", "group": "Fruit", "regime": "Phytosanitary"},
    {"hs": "0809 40", "description": "Plums and sloes, fresh", "group": "Fruit", "regime": "Phytosanitary"},
    {"hs": "0810 10", "description": "Strawberries, fresh", "group": "Fruit", "regime": "Phytosanitary"},
    {"hs": "0810 70", "description": "Persimmons, fresh", "group": "Fruit", "regime": "Phytosanitary"},
    {"hs": "0810 90", "description": "Fruit, fresh, other (including pomegranates)", "group": "Fruit", "regime": "Phytosanitary"},
    {"hs": "0813 10", "description": "Apricots, dried", "group": "Dried fruit", "regime": "Phytosanitary"},
    {"hs": "0813 20", "description": "Prunes, dried", "group": "Dried fruit", "regime": "Phytosanitary"},
    {"hs": "0813 40", "description": "Dried fruit, other", "group": "Dried fruit", "regime": "Phytosanitary"},
    {"hs": "0901 21", "description": "Coffee, roasted, not decaffeinated", "group": "Tea and coffee", "regime": "Phytosanitary"},
    {"hs": "0902 10", "description": "Green tea in packings ≤ 3 kg", "group": "Tea", "regime": "Phytosanitary"},
    {"hs": "0902 30", "description": "Black fermented tea in packings ≤ 3 kg", "group": "Tea", "regime": "Phytosanitary"},
    {"hs": "0902 40", "description": "Black fermented tea in packings > 3 kg", "group": "Tea", "regime": "Phytosanitary"},
    {"hs": "0904 22", "description": "Peppers, crushed or ground", "group": "Spices", "regime": "Phytosanitary"},
    {"hs": "0909 31", "description": "Cumin seeds, neither crushed nor ground", "group": "Spices", "regime": "Phytosanitary"},
    {"hs": "1001 99", "description": "Wheat and meslin, other", "group": "Cereals", "regime": "Phytosanitary"},
    {"hs": "1005 90", "description": "Maize (corn), other", "group": "Cereals", "regime": "Phytosanitary"},
    {"hs": "1006 30", "description": "Rice, semi-milled or wholly milled", "group": "Cereals", "regime": "Phytosanitary"},
    {"hs": "1101 00", "description": "Wheat or meslin flour", "group": "Milled products", "regime": "Phytosanitary"},
    {"hs": "1103 11", "description": "Groats and meal of wheat", "group": "Milled products", "regime": "Phytosanitary"},
    {"hs": "1107 10", "description": "Malt, not roasted", "group": "Milled products", "regime": "Phytosanitary"},
    {"hs": "1202 42", "description": "Groundnuts, shelled", "group": "Oilseeds", "regime": "Phytosanitary"},
    {"hs": "1204 00", "description": "Linseed", "group": "Oilseeds", "regime": "Phytosanitary"},
    {"hs": "1206 00", "description": "Sunflower seeds", "group": "Oilseeds", "regime": "Phytosanitary"},
    {"hs": "1207 40", "description": "Sesame seeds", "group": "Oilseeds", "regime": "Phytosanitary"},
    {"hs": "1209 91", "description": "Vegetable seeds for sowing", "group": "Oilseeds", "regime": "Phytosanitary"},
    {"hs": "1211 90", "description": "Plants used in pharmacy or perfumery, other (including liquorice root)", "group": "Medicinal plants", "regime": "Phytosanitary"},
    {"hs": "1507 90", "description": "Soya-bean oil, refined", "group": "Vegetable oils", "regime": "Phytosanitary"},
    {"hs": "1512 11", "description": "Sunflower-seed oil, crude", "group": "Vegetable oils", "regime": "Phytosanitary"},
    {"hs": "1512 19", "description": "Sunflower-seed oil, refined", "group": "Vegetable oils", "regime": "Phytosanitary"},
    {"hs": "1517 90", "description": "Edible mixtures of fats and oils, other", "group": "Vegetable oils", "regime": "Phytosanitary"},
    {"hs": "1602 32", "description": "Prepared or preserved meat of fowls", "group": "Prepared foods", "regime": "Veterinary"},
    {"hs": "1701 99", "description": "Cane or beet sugar, other", "group": "Prepared foods", "regime": "Phytosanitary"},
    {"hs": "1704 90", "description": "Sugar confectionery without cocoa, other", "group": "Prepared foods", "regime": "Phytosanitary"},
    {"hs": "1806 32", "description": "Chocolate in blocks, slabs or bars, not filled", "group": "Prepared foods", "regime": "Phytosanitary"},
    {"hs": "1902 19", "description": "Pasta, uncooked, other", "group": "Prepared foods", "regime": "Phytosanitary"},
    {"hs": "1905 31", "description": "Sweet biscuits", "group": "Prepared foods", "regime": "Phytosanitary"},
    {"hs": "2002 90", "description": "Tomatoes prepared or preserved, other (including tomato paste)", "group": "Prepared foods", "regime": "Phytosanitary"},
    {"hs": "2007 99", "description": "Jams, jellies and fruit purées, other", "group": "Prepared foods", "regime": "Phytosanitary"},
    {"hs": "2008 99", "description": "Fruit otherwise prepared or preserved, other", "group": "Prepared foods", "regime": "Phytosanitary"},
    {"hs": "2009 79", "description": "Apple juice, other", "group": "Prepared foods", "regime": "Phytosanitary"},
    {"hs": "2106 90", "description": "Food preparations not elsewhere specified, other", "group": "Prepared foods", "regime": "Phytosanitary"},
    {"hs": "2201 10", "description": "Mineral waters and aerated waters", "group": "Beverages", "regime": "Standard"},
    {"hs": "2202 10", "description": "Waters with added sugar or flavouring", "group": "Beverages", "regime": "Standard"},
    {"hs": "2204 21", "description": "Wine in containers holding ≤ 2 litres", "group": "Beverages", "regime": "Standard"},
    {"hs": "2208 90", "description": "Spirits and spirituous beverages, other", "group": "Beverages", "regime": "Standard"},
    {"hs": "2402 20", "description": "Cigarettes containing tobacco", "group": "Tobacco", "regime": "Standard"},
    {"hs": "2501 00", "description": "Salt and pure sodium chloride", "group": "Minerals", "regime": "Standard"},
    {"hs": "2515 12", "description": "Marble, merely cut into blocks or slabs", "group": "Minerals", "regime": "Standard"},
    {"hs": "2517 10", "description": "Pebbles, gravel and crushed stone", "group": "Minerals", "regime": "Standard"},
    {"hs": "2520 10", "description": "Gypsum and anhydrite", "group": "Minerals", "regime": "Standard"},
    {"hs": "2523 29", "description": "Portland cement, other", "group": "Minerals", "regime": "Standard"},
    {"hs": "2709 00", "description": "Petroleum oils, crude", "group": "Fuels", "regime": "Hazardous"},
    {"hs": "2710 19", "description": "Petroleum oils, other than crude", "group": "Fuels", "regime": "Hazardous"},
    {"hs": "2711 11", "description": "Natural gas, liquefied", "group": "Fuels", "regime": "Hazardous"},
    {"hs": "2711 21", "description": "Natural gas, in the gaseous state", "group": "Fuels", "regime": "Hazardous"},
    {"hs": "2814 10", "description": "Anhydrous ammonia", "group": "Chemicals", "regime": "Hazardous"},
    {"hs": "2836 30", "description": "Sodium hydrogencarbonate (baking soda)", "group": "Chemicals", "regime": "Hazardous"},
    {"hs": "3002 41", "description": "Vaccines for human medicine", "group": "Pharmaceutical", "regime": "Pharmaceutical"},
    {"hs": "3004 90", "description": "Medicaments, packaged for retail", "group": "Pharmaceutical", "regime": "Pharmaceutical"},
    {"hs": "3005 90", "description": "Wadding, gauze and bandages, other", "group": "Pharmaceutical", "regime": "Pharmaceutical"},
    {"hs": "3006 10", "description": "Sterile surgical catgut and similar sutures", "group": "Pharmaceutical", "regime": "Pharmaceutical"},
    {"hs": "3102 10", "description": "Urea, mineral fertiliser", "group": "Chemicals", "regime": "Hazardous"},
    {"hs": "3102 30", "description": "Ammonium nitrate", "group": "Chemicals", "regime": "Hazardous"},
    {"hs": "3105 20", "description": "Mineral fertilisers containing nitrogen, phosphorus and potassium", "group": "Chemicals", "regime": "Hazardous"},
    {"hs": "3208 10", "description": "Paints and varnishes based on polyesters", "group": "Chemicals", "regime": "Hazardous"},
    {"hs": "3304 99", "description": "Beauty or skin-care preparations, other", "group": "Cosmetics", "regime": "Standard"},
    {"hs": "3401 11", "description": "Soap for toilet use", "group": "Cosmetics", "regime": "Standard"},
    {"hs": "3402 50", "description": "Washing and cleaning preparations, put up for retail sale", "group": "Chemicals", "regime": "Standard"},
    {"hs": "3808 91", "description": "Insecticides", "group": "Chemicals", "regime": "Hazardous"},
    {"hs": "3901 10", "description": "Polyethylene, specific gravity < 0.94", "group": "Plastics", "regime": "Standard"},
    {"hs": "3902 10", "description": "Polypropylene", "group": "Plastics", "regime": "Standard"},
    {"hs": "3917 23", "description": "Tubes and pipes of polymers of vinyl chloride", "group": "Plastics", "regime": "Standard"},
    {"hs": "3923 21", "description": "Sacks and bags of polymers of ethylene", "group": "Plastics", "regime": "Standard"},
    {"hs": "4011 10", "description": "New pneumatic tyres for motor cars", "group": "Rubber", "regime": "Standard"},
    {"hs": "4104 11", "description": "Tanned bovine hides, full grains, unsplit", "group": "Leather", "regime": "Veterinary"},
    {"hs": "4107 11", "description": "Leather further prepared after tanning, full grains", "group": "Leather", "regime": "Veterinary"},
    {"hs": "4407 11", "description": "Coniferous wood sawn lengthwise, pine", "group": "Wood", "regime": "Phytosanitary"},
    {"hs": "4412 33", "description": "Plywood with an outer ply of non-coniferous wood", "group": "Wood", "regime": "Phytosanitary"},
    {"hs": "4818 10", "description": "Toilet paper", "group": "Paper", "regime": "Standard"},
    {"hs": "4819 10", "description": "Cartons and boxes of corrugated paper", "group": "Paper", "regime": "Standard"},
    {"hs": "5002 00", "description": "Raw silk, not thrown", "group": "Textiles", "regime": "Standard"},
    {"hs": "5201 00", "description": "Cotton, not carded or combed", "group": "Textiles", "regime": "Phytosanitary"},
    {"hs": "5205 12", "description": "Cotton yarn, single, uncombed", "group": "Textiles", "regime": "Standard"},
    {"hs": "5205 23", "description": "Cotton yarn, single, combed", "group": "Textiles", "regime": "Standard"},
    {"hs": "5206 12", "description": "Cotton yarn, under 85 % cotton, single, uncombed", "group": "Textiles", "regime": "Standard"},
    {"hs": "5208 52", "description": "Cotton fabric, printed, plain weave", "group": "Textiles", "regime": "Standard"},
    {"hs": "5209 42", "description": "Denim of cotton", "group": "Textiles", "regime": "Standard"},
    {"hs": "5407 61", "description": "Woven fabrics of polyester filament yarn", "group": "Textiles", "regime": "Standard"},
    {"hs": "5509 53", "description": "Yarn of polyester staple fibres mixed with cotton", "group": "Textiles", "regime": "Standard"},
    {"hs": "5601 21", "description": "Wadding of cotton", "group": "Textiles", "regime": "Standard"},
    {"hs": "5701 10", "description": "Carpets of wool, knotted", "group": "Carpets", "regime": "Standard"},
    {"hs": "5703 29", "description": "Carpets, tufted, of nylon or other polyamides, other", "group": "Carpets", "regime": "Standard"},
    {"hs": "6006 22", "description": "Knitted cotton fabric, dyed", "group": "Textiles", "regime": "Standard"},
    {"hs": "6104 62", "description": "Women's trousers of cotton, knitted", "group": "Apparel", "regime": "Standard"},
    {"hs": "6105 10", "description": "Men's shirts of cotton, knitted", "group": "Apparel", "regime": "Standard"},
    {"hs": "6109 10", "description": "T-shirts and singlets of cotton, knitted", "group": "Apparel", "regime": "Standard"},
    {"hs": "6110 20", "description": "Pullovers and cardigans of cotton, knitted", "group": "Apparel", "regime": "Standard"},
    {"hs": "6111 20", "description": "Babies' garments of cotton, knitted", "group": "Apparel", "regime": "Standard"},
    {"hs": "6115 95", "description": "Socks and hosiery of cotton, knitted", "group": "Apparel", "regime": "Standard"},
    {"hs": "6203 42", "description": "Men's trousers of cotton, not knitted", "group": "Apparel", "regime": "Standard"},
    {"hs": "6204 62", "description": "Women's trousers of cotton, not knitted", "group": "Apparel", "regime": "Standard"},
    {"hs": "6302 21", "description": "Bed linen of cotton, printed", "group": "Home textiles", "regime": "Standard"},
    {"hs": "6302 60", "description": "Toilet and kitchen linen of terry cotton", "group": "Home textiles", "regime": "Standard"},
    {"hs": "6402 99", "description": "Footwear with uppers of plastics, other", "group": "Footwear", "regime": "Standard"},
    {"hs": "6403 99", "description": "Footwear with uppers of leather, other", "group": "Footwear", "regime": "Standard"},
    {"hs": "6907 21", "description": "Ceramic tiles, water absorption ≤ 0.5 % by weight", "group": "Ceramics", "regime": "Standard"},
    {"hs": "7010 90", "description": "Glass bottles, jars and containers, other", "group": "Glass", "regime": "Standard"},
    {"hs": "7013 49", "description": "Glassware for table or kitchen, other", "group": "Glass", "regime": "Standard"},
    {"hs": "7208 51", "description": "Flat-rolled steel, hot-rolled, thickness > 10 mm", "group": "Metals", "regime": "Standard"},
    {"hs": "7210 49", "description": "Flat-rolled steel, zinc-plated, other", "group": "Metals", "regime": "Standard"},
    {"hs": "7213 10", "description": "Bars and rods of iron, hot-rolled, with indentations", "group": "Metals", "regime": "Standard"},
    {"hs": "7306 30", "description": "Welded tubes of iron, circular cross-section", "group": "Metals", "regime": "Standard"},
    {"hs": "7308 90", "description": "Structures and parts of structures, of iron or steel, other", "group": "Metals", "regime": "Standard"},
    {"hs": "7403 11", "description": "Refined copper cathodes and sections of cathodes", "group": "Metals", "regime": "Standard"},
    {"hs": "7408 11", "description": "Copper wire, cross-sectional dimension > 6 mm", "group": "Metals", "regime": "Standard"},
    {"hs": "7601 10", "description": "Aluminium, unwrought, not alloyed", "group": "Metals", "regime": "Standard"},
    {"hs": "7604 21", "description": "Hollow profiles of aluminium alloys", "group": "Metals", "regime": "Standard"},
    {"hs": "7901 11", "description": "Zinc, unwrought, not alloyed, ≥ 99.99 %", "group": "Metals", "regime": "Standard"},
    {"hs": "8413 70", "description": "Centrifugal pumps, other", "group": "Machinery", "regime": "Standard"},
    {"hs": "8418 10", "description": "Combined refrigerator-freezers with separate doors", "group": "Machinery", "regime": "Standard"},
    {"hs": "8450 11", "description": "Fully automatic washing machines, capacity ≤ 10 kg", "group": "Machinery", "regime": "Standard"},
    {"hs": "8471 30", "description": "Portable automatic data-processing machines ≤ 10 kg", "group": "Electronics", "regime": "Standard"},
    {"hs": "8481 80", "description": "Taps, cocks and valves, other", "group": "Machinery", "regime": "Standard"},
    {"hs": "8501 52", "description": "AC motors, multi-phase, 750 W – 75 kW", "group": "Machinery", "regime": "Standard"},
    {"hs": "8504 34", "description": "Transformers, power handling capacity > 500 kVA", "group": "Machinery", "regime": "Standard"},
    {"hs": "8517 13", "description": "Smartphones", "group": "Electronics", "regime": "Standard"},
    {"hs": "8528 72", "description": "Television reception apparatus, colour", "group": "Electronics", "regime": "Standard"},
    {"hs": "8544 49", "description": "Electric conductors for a voltage ≤ 1,000 V, other", "group": "Electronics", "regime": "Standard"},
    {"hs": "8701 93", "description": "Agricultural tractors, engine power 37–75 kW", "group": "Vehicles", "regime": "Standard"},
    {"hs": "8702 10", "description": "Buses with compression-ignition engine", "group": "Vehicles", "regime": "Standard"},
    {"hs": "8703 22", "description": "Motor cars, spark-ignition, 1,000–1,500 cc", "group": "Vehicles", "regime": "Standard"},
    {"hs": "8703 23", "description": "Motor cars, spark-ignition, 1,500–3,000 cc", "group": "Vehicles", "regime": "Standard"},
    {"hs": "8704 21", "description": "Motor vehicles for the transport of goods, diesel, ≤ 5 t", "group": "Vehicles", "regime": "Standard"},
    {"hs": "8708 29", "description": "Parts of bodies of motor vehicles, other", "group": "Machinery", "regime": "Standard"},
    {"hs": "8708 99", "description": "Parts of motor vehicles, other", "group": "Machinery", "regime": "Standard"},
    {"hs": "8716 39", "description": "Trailers and semi-trailers for the transport of goods, other", "group": "Vehicles", "regime": "Standard"},
    {"hs": "9018 39", "description": "Needles, catheters and cannulae", "group": "Pharmaceutical", "regime": "Pharmaceutical"},
    {"hs": "9018 90", "description": "Instruments and appliances used in medical sciences, other", "group": "Pharmaceutical", "regime": "Pharmaceutical"},
    {"hs": "9401 61", "description": "Upholstered seats with wooden frames", "group": "Furniture", "regime": "Standard"},
    {"hs": "9403 30", "description": "Wooden furniture of a kind used in offices", "group": "Furniture", "regime": "Standard"},
    {"hs": "9506 91", "description": "Articles and equipment for general physical exercise", "group": "Sporting goods", "regime": "Standard"},
    {"hs": "9619 00", "description": "Sanitary towels, napkins and similar articles", "group": "Hygiene", "regime": "Standard"},
  ],
};

const UNITS: Registry = {
  slug: "units",
  name: "Units of measure",
  blurb: "Mass, volume, count, packaging and equipment units used on declarations. UN/ECE Recommendation 20 codes.",
  authored: true,
  source: null,
  columns: [{"key": "code", "label": "Code"}, {"key": "name", "label": "Unit"}, {"key": "dimension", "label": "Dimension"}],
  rows: [
    {"code": "KGM", "name": "Kilogram", "dimension": "Mass"},
    {"code": "TNE", "name": "Tonne (metric)", "dimension": "Mass"},
    {"code": "LTR", "name": "Litre", "dimension": "Volume"},
    {"code": "MTQ", "name": "Cubic metre", "dimension": "Volume"},
    {"code": "NMB", "name": "Number of items", "dimension": "Count"},
    {"code": "PCE", "name": "Piece", "dimension": "Count"},
    {"code": "PAL", "name": "Pallet", "dimension": "Packaging"},
    {"code": "BOX", "name": "Box", "dimension": "Packaging"},
    {"code": "CT", "name": "Container, 20 ft", "dimension": "Equipment"},
    {"code": "CT40", "name": "Container, 40 ft", "dimension": "Equipment"},
  ],
};

const TRANSPORT_MODES: Registry = {
  slug: "transport-modes",
  name: "Transport modes",
  blurb: "The modes the published catalogue is divided by.",
  authored: false,
  source: "Read from the procedure catalogue of 245 procedures. 46 publish no mode at all. Refreshed when the portal republishes.",
  columns: [{"key": "mode", "label": "Mode"}, {"key": "procedures", "label": "Procedures", "numeric": true}, {"key": "steps", "label": "Steps", "numeric": true}],
  rows: [
    {"mode": "by train", "procedures": 121, "steps": 3164},
    {"mode": "by road", "procedures": 59, "steps": 1682},
    {"mode": "(not published)", "procedures": 46, "steps": 260},
    {"mode": "by air", "procedures": 19, "steps": 495},
  ],
};

const LOCATIONS: Registry = {
  slug: "locations",
  name: "Counters & locations",
  blurb: "Every physical place a published step sends a person to.",
  authored: false,
  source: "Derived from 245 published procedures; refreshed when the portal republishes.",
  columns: [{"key": "location", "label": "Location", "wide": true}, {"key": "steps", "label": "Steps", "numeric": true}, {"key": "procedures", "label": "Procedures", "numeric": true}],
  rows: [
    {"location": "Commodity cash desk", "steps": 363, "procedures": 140},
    {"location": "Freight acceptance and handover Room", "steps": 228, "procedures": 76},
    {"location": "Storage", "steps": 180, "procedures": 72},
    {"location": "Group of customs control and customs clearance", "steps": 166, "procedures": 124},
    {"location": "Freight forwarding company", "steps": 153, "procedures": 51},
    {"location": "Warehouse / Location of goods", "steps": 147, "procedures": 73},
    {"location": "Department of Examination of Preferential Goods \"3rd floor\"", "steps": 146, "procedures": 49},
    {"location": "Customs warehouse", "steps": 121, "procedures": 90},
    {"location": "Border control", "steps": 116, "procedures": 57},
    {"location": "Transportation  Unit \"Room 128, 1st Floor\"", "steps": 111, "procedures": 37},
    {"location": "Customs control zone", "steps": 109, "procedures": 59},
    {"location": "Inspectors of the Department on freight and commerce Room 402, 4th floor\"", "steps": 109, "procedures": 109},
    {"location": "Administration department", "steps": 92, "procedures": 54},
    {"location": "Customs warehouse checkpoint", "steps": 83, "procedures": 57},
    {"location": "Accounting department \"Room 127, 1st Floor\"", "steps": 64, "procedures": 32},
    {"location": "Department on freight and commerce \"Room 405, 4th Floor\"", "steps": 64, "procedures": 32},
    {"location": "Customs control", "steps": 62, "procedures": 59},
    {"location": "Deputy Chief of the Department of examination of preferential goods \"Room 36, 3rd floor\"", "steps": 61, "procedures": 49},
    {"location": "Online banking system", "steps": 59, "procedures": 58},
    {"location": "Weight and radiation control", "steps": 58, "procedures": 57},
    {"location": "Customs inspection area", "steps": 58, "procedures": 57},
    {"location": "Inspection and screening station", "steps": 58, "procedures": 57},
    {"location": "Passport  control point", "steps": 58, "procedures": 57},
    {"location": "Logistics department", "steps": 54, "procedures": 18},
    {"location": "Place of loading / branch line", "steps": 51, "procedures": 51},
    {"location": "Office of the inspector on the border checkpoint for plant quarantine", "steps": 35, "procedures": 19},
    {"location": "Fumigation (disinfection) division", "steps": 30, "procedures": 30},
    {"location": "Cash desk \"First floor\"", "steps": 30, "procedures": 17},
    {"location": "Department of carriage conditions \"Room 313, 3rd Floor\"", "steps": 26, "procedures": 26},
    {"location": "Contracting Department \"Room 212, 2nd floor\"", "steps": 26, "procedures": 13},
    {"location": "Information department of Postal cargo complex", "steps": 26, "procedures": 7},
    {"location": "Sanitary-epidemiological service laboratory", "steps": 24, "procedures": 24},
    {"location": "Airport's Checkpoint", "steps": 24, "procedures": 17},
    {"location": "Cargo storage place", "steps": 24, "procedures": 19},
    {"location": "Pass issuance room \"Room 109, 1st floor\"", "steps": 22, "procedures": 17},
    {"location": "Cargo sales agent", "steps": 21, "procedures": 7},
    {"location": "Border veterinary control checkpoint", "steps": 20, "procedures": 19},
    {"location": "Department of customs clearance \"First Window, 1st floor in secured zone\"", "steps": 17, "procedures": 17},
    {"location": "Border checkpoint for plant quarantine", "steps": 14, "procedures": 13},
    {"location": "Reception \"Room 1, 1st floor\"", "steps": 10, "procedures": 2},
    {"location": "The agent in booking cargoes \"Room 102, 1st floor\"", "steps": 10, "procedures": 10},
    {"location": "Dangerous goods department \"Room 101, 1st floor\"", "steps": 10, "procedures": 10},
    {"location": "Aviation safety inspection department", "steps": 10, "procedures": 10},
    {"location": "Postal cargo complex at Tashkent International Airport named by Islam Karimov", "steps": 10, "procedures": 10},
    {"location": "Department of customs clearance \"Second Window, 1st floor in secured zone\"", "steps": 7, "procedures": 7},
    {"location": "Certification department \"Rooms 201-214, 2nd floor\"", "steps": 7, "procedures": 7},
    {"location": "Department for certification FPCCP \"427 room, 4th floor\"", "steps": 5, "procedures": 5},
    {"location": "Insurance department", "steps": 4, "procedures": 1},
    {"location": "Department of financial assistance in the transportation of exported products \"ROOM 3, 2ND FLOOR\"", "steps": 2, "procedures": 1},
    {"location": "Operating Hall", "steps": 2, "procedures": 2},
    {"location": "Single portal of interactive state services", "steps": 2, "procedures": 1},
    {"location": "Customs broker", "steps": 1, "procedures": 1},
    {"location": "Place of medical equipment installation", "steps": 1, "procedures": 1},
    {"location": "Technic office", "steps": 1, "procedures": 1},
    {"location": "Border crossing point by rail", "steps": 1, "procedures": 1},
    {"location": "State nature protection comittee", "steps": 1, "procedures": 1},
  ],
};

export const REGISTRIES: Registry[] = [COUNTRIES, CURRENCIES, COMMODITY_CODES, UNITS, TRANSPORT_MODES, LOCATIONS];

export const registryFor = (slug: string): Registry | undefined => REGISTRIES.find((r) => r.slug === slug);
