/* Demo pack: invented documents and values that walk a case through every
 * step, for every procedure. The scenario JSON is the single source - the
 * Python generator (apps/docai/demo/generate_demo.py) renders the documents
 * from it, and this module maps each step need to its demo. 868's scenario is
 * written by hand; the others are generated by scripts/demo/build-scenarios.ts. */

import scenario161 from "./data/scenario-161.json";
import scenario306 from "./data/scenario-306.json";
import scenario325 from "./data/scenario-325.json";
import scenario477 from "./data/scenario-477.json";
import scenario540 from "./data/scenario-540.json";
import scenario57 from "./data/scenario-57.json";
import scenario707 from "./data/scenario-707.json";
import scenario782 from "./data/scenario-782.json";
import scenario868 from "./data/scenario-868.json";
import scenario924 from "./data/scenario-924.json";
import type { Need } from "../steps/next";

export type DemoDocument = {
  id: string;
  file: string;
  template: string;
  title: string;
  docType: string | null;
  labels: string[];
  steps: number[];
  output: boolean;
  fields: Record<string, string>;
  body?: string;
  stamp?: string;
};

export type DemoScenario = {
  procedureId: string;
  title: string;
  note: string;
  shipment: Record<string, string | string[]>;
  values: Record<string, string>;
  documents: DemoDocument[];
};

const SCENARIOS: Record<string, DemoScenario> = Object.fromEntries(
  [scenario161, scenario306, scenario325, scenario477, scenario540, scenario57, scenario707, scenario782, scenario868, scenario924].map((s) => [
    s.procedureId,
    s as unknown as DemoScenario,
  ]),
);

export const DEMO_PROCEDURES = Object.keys(SCENARIOS);

export const demoFor = (procedureId: string): DemoScenario | null => SCENARIOS[procedureId] ?? null;

export const demoFileUrl = (procedureId: string, doc: DemoDocument) => `/demo/${procedureId}/${doc.file}`;

/** The demo document an uploaded file is, by its file name - within one procedure's pack when known. */
export function demoDocumentByFile(fileName: string, docType: string | null, procedureId?: string | null): { scenario: DemoScenario; document: DemoDocument } | null {
  const base = fileName.replace(/\\/g, "/").split("/").pop()?.toLowerCase() ?? "";
  const scenarios = procedureId && SCENARIOS[procedureId] ? [SCENARIOS[procedureId]] : Object.values(SCENARIOS);
  for (const scenario of scenarios) {
    const document = scenario.documents.find((d) => d.file.toLowerCase() === base && (!docType || d.docType === docType));
    if (document) return { scenario, document };
  }
  return null;
}

export type DemoMatch = { kind: "document"; document: DemoDocument; url: string } | { kind: "value"; value: string };

/** The demo that satisfies one need at one step, if the procedure has a demo pack. */
export function demoForNeed(procedureId: string, need: Need, stepNum: number): DemoMatch | null {
  const scenario = demoFor(procedureId);
  if (!scenario) return null;

  if (need.kind === "value") {
    const value = scenario.values[need.label];
    return value ? { kind: "value", value } : null;
  }
  if (need.kind !== "document") return null;

  const labelled = scenario.documents.filter((d) => d.labels.includes(need.label));
  // A step's output belongs to that step (each payment has its own receipt);
  // an input document is shared by every step that names it.
  const pool = need.output ? labelled.filter((d) => d.output && d.steps.includes(stepNum)) : labelled.filter((d) => !d.output);
  const pick =
    pool.find((d) => d.steps.includes(stepNum)) ??
    pool[0] ??
    (!need.output && need.docType ? scenario.documents.find((d) => !d.output && d.docType === need.docType) : undefined);
  return pick ? { kind: "document", document: pick, url: demoFileUrl(procedureId, pick) } : null;
}
